{% set name = "mesa" %}
{% set version = "0.8.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/mesa/Mesa-{{ version }}.tar.gz
  sha256: 1381f5d3a8a7c4c06978bddfe8a60d494db28004876171bd63298c308ca66235

build:
  number: 0
  noarch: python
  entry_points:
    - mesa=mesa.main:cli
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3
  run:
    - click
    - cookiecutter
    - networkx
    - numpy
    - pandas
    - python >=3
    - tornado
    - tqdm

test:
  imports:
    - mesa
  commands:
    - mesa --help

about:
  home: https://github.com/projectmesa/mesa
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Agent-based modeling (ABM) in Python 3+
  description: |
    Mesa is an Apache2 licensed agent-based modeling (or ABM) 
    framework in Python. It allows users to quickly create agent-based 
    models using built-in core components (such as spatial grids and 
    agent schedulers) or customized implementations; visualize them 
    using a browser-based interface; and analyze their results using 
    Python's data analysis tools. Its goal is to be the Python 3-based 
    alternative to NetLogo, Repast, or MASON.
  doc_url: https://mesa.readthedocs.io
  dev_url: https://github.com/projectmesa/mesa

extra:
  recipe-maintainers:
    - estshorter
    - jackiekazil
    - dmasad
