{% set name = "mesa" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/mesa/{{ name }}-{{ version }}.tar.gz
  sha256: c171c2c94934e44cf8c9ee5ad6b2970b228f64c2bb6d1ef1679ae90f9984694c

build:
  number: 0
  noarch: python
  entry_points:
    - mesa=mesa.main:cli
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python >=3
    - hatchling
  run:
    - click
    - cookiecutter
    - networkx
    - numpy
    - pandas
    - python >=3.8
    - tornado
    - tqdm
    - matplotlib-base
    - solara
    - mesa-viz-tornado~ =0.1.0,>=0.1.3

test:
  imports:
    - mesa
  commands:
    - pip check
    - mesa --help
  requires:
    - pip

about:
  home: https://github.com/projectmesa/mesa
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Agent-based modeling (ABM) in Python 3+
  description: |
    Mesa is an Apache2 licensed agent-based modeling (or ABM) 
    framework in Python. It allows users to quickly create agent-based 
    models using built-in core components (such as spatial grids and 
    agent schedulers) or customized implementations; visualize them 
    using a browser-based interface; and analyze their results using 
    Python's data analysis tools. Its goal is to be the Python 3-based 
    alternative to NetLogo, Repast, or MASON.
  doc_url: https://mesa.readthedocs.io

extra:
  recipe-maintainers:
    - jackiekazil
    - dmasad
    - adamamer20
