{% set name = "mesa" %}
{% set version = "0.8.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/mesa/Mesa-{{ version }}.tar.gz
  sha256: 4bb8bbb54aa07ad1418260621fd2f1da585249aa024c934d65ac441bb67ec762

build:
  number: 0
  noarch: python
  entry_points:
    - mesa = mesa.main:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.8
    - click
    - cookiecutter
    - matplotlib-base
    - mesa-viz-tornado >=0.1.3,>=0.1.0,<0.2.dev0
    - networkx
    - numpy
    - pandas
    - solara
    - tqdm

test:
  imports:
    - mesa
  commands:
    - pip check
    - mesa --help
  requires:
    - pip

about:
  home: https://github.com/projectmesa/mesa
  summary: Agent-based modeling (ABM) in Python 3+
  license: Apache-2.0 AND MIT
  license_file:
    - LICENSE.txt
  description: |
    Mesa is an Apache2 licensed agent-based modeling (or ABM) 
    framework in Python. It allows users to quickly create agent-based 
    models using built-in core components (such as spatial grids and 
    agent schedulers) or customized implementations; visualize them 
    using a browser-based interface; and analyze their results using 
    Python's data analysis tools. Its goal is to be the Python 3-based 
    alternative to NetLogo, Repast, or MASON.
  doc_url: https://mesa.readthedocs.io

extra:
  recipe-maintainers:
    - estshorter
    - jackiekazil
    - dmasad
